name: Dart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test latest stable, beta, dev, and main channels + last stable release
        # prior to the introduction of the unified `dart` developer tool.
        channel: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          channel: ${{ matrix.sdk }}

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart
  test-dev:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test latest stable, beta, dev, and main channels + last stable release
        # prior to the introduction of the unified `dart` developer tool.
        channel: [dev]
        version: ["2.1.0-12.1.pre"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          channel: ${{ matrix.sdk }}
          version: ${{ matrix.version }}

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart

  test_pub:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          channel: ${{ matrix.channel }}

      - name: Global activate + run
        run: |
          dart pub global activate stagehand
          mkdir testapp
          cd testapp
          stagehand console-simple
          dart pub get
          dart run
