name: Flutter SDK for macOS

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]
  schedule:
    # https://crontab.guru/#40_10_*_*_*
    - cron: '40 10 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow.name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/flutter.yml
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 3.0.0
    with:
      runs-on: macos-latest # Apple M1 Silicon
      version: ${{ matrix.version }}
