name: Flutter SDK for Linux

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]
  schedule:
    # https://crontab.guru/#40_10_*_*_*
    - cron: '40 10 * * *'
  workflow_dispatch:
  
jobs:
  test:
    uses: ./.github/workflows/flutter.yml
    strategy:
      matrix:
        version:
          - latest
          - 3.0.0
    with:
      runs-on: ubuntu-latest
      version: ${{ matrix.version }}
